name: Build and Push Images to GitHub Container Registry (GHCR)
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - feature/*
      - practice
  workflow_dispatch:
jobs:
  # Linting
  # https://github.com/marketplace/actions/upload-a-build-artifact
  # Security Scanning
  # https://github.com/marketplace/actions/container-image-scan
  # Caching
  # https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
  Build-And-Push-Application:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      # https://github.com/marketplace/actions/checkout
      - name: Check out repository code
        uses: actions/checkout@v2
      # https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
      # https://blog.codecentric.de/en/2021/03/github-container-registry/
      # https://github.com/jonashackt/docker-hello-world/blob/main/.github/workflows/publish.yml
      - name: Build the frontend Docker image
        run: |
          docker build ./frontend --tag ghcr.io/ernestboey/bootcamp-gds-frontend:latest
          docker push ghcr.io/ernestboey/bootcamp-gds-frontend:latest
      - name: Build the backend Docker image
        run: |
          docker build ./backend --tag ghcr.io/ernestboey/bootcamp-gds-backend:latest
          docker push ghcr.io/ernestboey/bootcamp-gds-backend:latest
# name: GitHub Actions Demo
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v2
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#           ls /
#       - run: echo "ğŸ This job's status is ${{ job.status }}."
